### ISSUE TITLE
PCC: allow permutations of only letters

### ISSUE THREAD

**Issue by LadnerJonas** [keinenclue/keinenclue.github.io#18]
(A,H)(B,D)(F,E) and stuff like that, is currently invalid input. I think this can be fixed quite easily. In the meantime, you can just encode the letters to digits, like A -> 1.

**Comment by dorianim** [comment]
Could you send a PR?

**Comment by LadnerJonas** [comment]
After taking a look at the code: I do not think it is worth the time... As stated above, there is an easy way to navigate around this issue.

**Comment by dorianim** [comment]
Shouldn't be too difficult:
- Use a regex to check if the string is composed of letters or numbers
- if composed of letters:
  - Replace letters with numbers
  - do calculation
  - Replace numbers with letters
