### ISSUE TITLE
Id not parsed correctly

### ISSUE THREAD

**Issue by 16domsim** [keinenclue/keinenclue.github.io#8]
For example  [https://keinenclue.github.io/pcc/?f=Id%20(2,%203)](url)

**Comment by 16domsim** [comment]
For example  [https://keinenclue.github.io/pcc/?f=Id%20(2,%203)](url)

**Comment by dorianim** [comment]
Yes, true. This was caused by 76203cc1a5b0b370ecc55fb85d30f02523c3663d
We need some other way to split the string. Maybe regex.
